apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: node-express-cronjob
spec:
  #  Cron 格式串  Seconds Minutes Hours DayofMonth Month DayofWeek Year  每1分钟
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: node-express
            image: huangyanyan/node-express-service
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
