apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: node-express-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: node-express-service
          servicePort: 8080
